export const contactData = [
  {
    role: "registrant",
    fullName: "Jedidiah Onwubiko",
    address: "12 Mandela Area Sauka Kahuta, Minna, Niger, 920101, NG",
    email: "solomon@hordanso.com",
    phone: "+234.7062957194",
    organization: "Jedybrown Ventures",
    city: "Minna",
    state: "Niger",
    postalCode: "920101",
    countryCode: "NG",
  },
  {
    role: "admin",
    fullName: "Faith HDS",
    address: "123 Elm St, Springfield, IL, 62701, US",
    email: "faith@hordanso.com",
    phone: "+234.8060440510",
    organization: "Hordanso LTD",
    city: "Springfield",
    state: "IL",
    postalCode: "62701",
    countryCode: "US",
  },
];
